### ISSUE TITLE
npm run build failed on examples/*

### ISSUE THREAD

**Issue by asendia** [malte-wessel/minimal-flux#2]
1. clone minimal-flux
2. cd to examples/todo
3. npm install
4. npm run build

Is there anything I missed?

npm ERR! Linux 3.16.0-31-generic
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "run" "build"
npm ERR! node v1.5.1
npm ERR! npm  v2.7.0
npm ERR! code ELIFECYCLE
npm ERR! minimal-flux-todo-example@0.1.0 build: `browserify src/app.js -t babelify > build.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the minimal-flux-todo-example@0.1.0 build script 'browserify src/app.js -t babelify > build.js'.

**Comment by malte-wessel** [comment]
Whoops, my bad. I forgot to mention, that you first need to run `npm install` in the minimal-flux root directory, since the examples require the source files directly. Thanks for the hint!
