### ISSUE TITLE
Incomplete Chat Example?

### ISSUE THREAD

**Issue by claydiffrient** [malte-wessel/minimal-flux#7]
I've been working on using minimal-flux in an application I'm developing, and I'm trying to figure out where to handle sending data to the server.  I was hoping to find the answer in the chat example, however I found it was sorta missing.  I can't find anywhere that ChatWebAPIUtils.createMessage is being called.  So I don't think a message is ever actually sent to the server to be completed.

Thoughts?

**Comment by malte-wessel** [comment]
Oh, you are right. There are two lines missing in the message actions. It should be

````javascript

class MessageActions extends Actions {

  createMessage(text, threadId) {
    this.dispatch('createMessage', text, threadId);
    var message = ChatMessageUtils.getCreatedMessageData(text, threadId);
    ChatWebAPIUtils.createMessage(message);
  }
}

````
I will fix that. The example is taken from the [original flux repository](https://github.com/facebook/flux/tree/master/examples/flux-chat). The part where `ChatWebAPIUtils.createMessage(message);` is called [can be found here](https://github.com/facebook/flux/blob/master/examples/flux-chat/js/actions/ChatMessageActionCreators.js#L22-L30).

Thanks!

**Comment by claydiffrient** [comment]
Thanks @malte-wessel especially for your circular dependency comments, since that was one of the major problems I was having in my app.  Glad to see there is a way around it. :)

**Comment by malte-wessel** [comment]
:+1:
